on: push # 触发此文件运行的条件
name: CI/CD # 此工作流程（workflow）的名字
jobs:
  FTP-Deploy-Action:
    name: CI&CD # 此任务（job）的名字
    runs-on: ubuntu-latest # 运行环境
    steps:
      - uses: actions/checkout@v4 # 切换分支到main
        with:
          fetch-depth: 2

      - name: Use Node.js 22.x
        uses: actions/setup-node@v4 # 使用node环境
        with:
          node-version: '22.x' # 版本22，与本地环境保持一致

      # - name: Cache node modules
      #   id: cache # 缓存id
      #   uses: actions/cache@v2
      #   env:
      #     cache-name: cache-node-modules # 缓存名字
      #   with:
      #     path: node_modules # 缓存路径
      #     key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('package.json') }} # 缓存标识

      - name: Install pnpm
        run: npm i pnpm -g

      - name: Install Dependencies
        # if: steps.cache.outputs.cache-hit != 'true' # 如果没有缓存的话
        run: pnpm i # 安装依赖

      - name: Build Packages
        run: pnpm run build #  打包文件
        
      # # 如果FTP-Deploy-Action出现，Dirty repository: Having uncommitted changes. 问题时，使用以下注释步骤解决问题
      # - name: reset git
      #   run: git reset --hard

      - name: Deploy to SFTP Server
        uses: vfiee/sftp-upload-action@v1.0
        with:
          server: 47.120.71.238 # 阿里云ECS服务器地址
          username: ${{ secrets.FTP_USERNAME }} # SFTP用户名
          password: ${{ secrets.FTP_PASSWORD }} # SFTP密码
          port: 22 # SFTP端口
          local-dir: ./.vitepress/dist # VitePress构建输出目录
          remote-dir: /usr/local/nginx/html/blog # 服务器目标目录

