# 方案2: 使用 SSH 私钥认证的版本
on: push
name: CI/CD

jobs:
  FTP-Deploy-Action:
    name: CI&CD
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: Install pnpm
        run: npm i pnpm -g

      - name: Install Dependencies
        run: pnpm i

      - name: Build Packages
        run: pnpm run build

      # 使用 SSH 私钥认证（更安全）
      - name: Deploy to SFTP Server with SSH Key
        uses: appleboy/scp-action@v0.1.7
        with:
          host: 47.120.71.238
          username: ${{ secrets.FTP_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }} # 使用SSH私钥而不是密码
          port: 22
          source: "./.vitepress/dist/*"
          target: "/usr/local/nginx/html/blog"
          strip_components: 3
          overwrite: true